version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.10
    commands:
      - pwd
      - ls -lrt
      - npm install
      - npm install -g @angular/cli
      - npm update
      - ls -lrt
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=production
      - npm prune --production
  post_build:
    commands:
      - mv appspec.yml dist/
      - cd dist
      - echo Build completed on `date`
artifacts:
  files:
    - "./**/*"
